[package]
name = "rust-voxel-blocks"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
env_logger = "0.11.8"
glam = { version = "0.30.10", features = ["bytemuck"] }
pollster = "0.4.0"
wgpu = "27.0.1"
winit = "0.30.12"
